version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-nexus
    environment:
      - VIRTUAL_HOST=nexus.backendteam.xyz
      - LETSENCRYPT_HOST=nexus.backendteam.xyz
      - LETSENCRYPT_EMAIL=email@nexus.backendteam.xyz

    volumes:
      - ./nginx/nexus.conf:/etc/nginx/conf.d/default.conf
      #- ${NGINX_DEFAULT_CONF:-./nginx/default.con}:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ${NGINX_SSL_CERT:-./certs/self_signed_cert.pem}:/etc/nginx/ssl/server.crt # uncomment for SSL
      - ${NGINX_SSL_KEY:-./certs/self_signed_key.pem}:/etc/nginx/ssl/server.key   # uncomment for SSL
    restart: always
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - ./nexus-data:/nexus-data
    ports:
      - "8081:8081"

networks:
  default:
    external:
      name: nginx-proxy-network