version: '3.6'
services:
  nginx:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=site1.com
      - LETSENCRYPT_HOST=site1.com
      - LETSENCRYPT_EMAIL=email@site1.com
    volumes:                     
      - .:/etc/nginx/conf.d
networks:
  default:
    external:
      name: nginx-proxy-network