version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - VIRTUAL_HOST=jenkin.backendteam.xyz
      - LETSENCRYPT_HOST=jenkin.backendteam.xyz
      - LETSENCRYPT_EMAIL=email@jenkin.backendteam.xyz
    volumes:
      - .:/etc/nginx/conf.d
      #- ${NGINX_DEFAULT_CONF:-./nginx/default.con}:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ${NGINX_SSL_CERT:-./certs/self_signed_cert.pem}:/etc/nginx/ssl/server.crt # uncomment for SSL
      - ${NGINX_SSL_KEY:-./certs/self_signed_key.pem}:/etc/nginx/ssl/server.key   # uncomment for SSL
    restart: always
  jenkins:
    image: jenkins.nginx.docker:lts
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - '2022:22'
      - '50000:50000'
      - '50022:50022'
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UID_JENKINS=${UID_JENKINS:-1000}
      - GID_JENKINS=${GID_JENKINS:-1000}
      - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
    restart: always

networks:
  default:
    external:
      name: nginx-proxy-network